apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  annotations:
      metallb.universe.tf/allow-shared-ip: shared
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      -  192.168.99.186-192.168.99.186
