apiVersion: apps/v1
kind: Deployment
metadata:
   name: myapp-deploy
   labels:
      app: myapp
      type: front-end
spec:
   template:
    metadata:
       name: myapp-pod
       labels:
          app: myapp
          type: frontend
    spec:
      containers:
      - name: simple-api
        image: zqasem/simple-api:2.4
   replicas: 1
   selector:
    matchLabels:
      app: myapp
      type: frontend