apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploymentt
spec:
  selector:
    matchLabels:
      app: ngx
  replicas: 1
  template:
    metadata:
      labels:
        app: ngx
    spec:
      containers:
      - name: nginx
        imagePullPolicy: Never
        image: nginx_docker
        ports:
        - containerPort: 80