apiVersion: v1
kind: Service
metadata:
   name: nginx-service
spec:
   # type: NodePort
   ports:
    - name: https
      protocol: TCP
      targetPort: 80
      port: 80
      # nodePort: 80
   selector:
      app: ngx