apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  name: grafana
spec:
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  selector:
    app: grafana
  type: LoadBalancer

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: grafana-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: garfana-pv-volume
  labels:
    type: local
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data"

---

apiVersion: apps/v1
kind: Deployment
metadata: 
  name: grafana
  labels:
    app: grafana
spec:
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
      volumes:
        - name: grafana-pv
          persistentVolumeClaim:
            claimName: grafana-pv-claim
