apiVersion: v1
kind: Service
metadata:
   name: nginx
   annotations:
      metallb.universe.tf/allow-shared-ip: shared
spec:
   selector:
     app: nginx
   type: LoadBalancer
   ports:
      - port: 80
        name: http
        targetPort: 80
      - port: 443
        name: https
        targetPort: 443
      - port: 22
        name: ssh
        targetPort: 22

---

apiVersion: apps/v1
kind: Deployment
metadata:
   name: nginx
   labels:
      app: nginx
spec:
   selector:
      matchLabels:
         app: nginx
   template:
      metadata:
         labels:
            app: nginx
      spec:
         containers:
         - name: nginx
           image: nginx
           imagePullPolicy: Never
           ports:
           - containerPort: 80
             name: http
           - containerPort: 443
             name: https
           - containerPort: 22
             name: ssh