apiVersion: apps/v1
kind: Deployment
metadata:
   name: nginx
   labels:
      app: nginx
spec:
   selector:
      matchLabels:
         app: nginx
   template:
      metadata:
         labels:
            app: nginx
      spec:
         containers:
         - name: nginx-containers
           image: nginx
           imagePullPolicy: Never
           ports:
           - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
   name: nginx
spec:
   selector:
     app: nginx
   type: LoadBalancer
   ports:
   - port: 80
     targetPort: 8080