apiVersion: v1
kind: Service
metadata:
   name: wordpress
spec:
   selector:
     app: wordpress
   type: LoadBalancer
   ports:
   - port: 5050
     targetPort: 5050

---

apiVersion: apps/v1
kind: Deployment
metadata:
   name: wordpress
   labels:
      app: wp
spec:
   selector:
      matchLabels:
         app: wp
   template:
      metadata:
         labels:
            app: wp
      spec:
         containers:
         - name: wordpress
           image: wp
           imagePullPolicy: Never
           ports:
           - containerPort: 5050